### ISSUE TITLE
[Automation - BUG] Duplicate session trace being recorded

### ISSUE THREAD

**Issue by McKiko030** [microsoft/powercat-automation-kit#408]
### Describe the issue

Duplicate session trace being recorded.

E.g. The flow runs for 4 times.

When check in Flow Session Traces, it has 7 sessions with 4 unique and 3 duplicate sessions.

### Expected Behavior

Flow Session Traces should only have 4 sessions recorded.

### What component are you experiencing the issue with?

Other

### What solution version are you using?

May 2024

### What app or flow are you having the issue with?

 Sync Flow Session Trace (Flow Session Trigger)

### Steps To Reproduce

[Automation Kit - Flow with & without PAD Test Result.xlsx](https://github.com/user-attachments/files/15988551/Automation.Kit.-.Flow.with.without.PAD.Test.Result.xlsx)

**Comment by praveen-pulagam-gl** [comment]
@McKiko030, There is no issue in the flow "**Sync Flow Session Trace (Flow Session Trigger)**". The flow gets triggered whenever there is a change in the **Flow Session** entity and logs into the **Flow Session Trace** entity. So, there could be multiple entries in the "Flow Session Trance" entity for each desktop flow run.

In your case, **Flow Session Trace** have 7 entries for 4 desktop flow runs and **Flow Session** entity will have 4 entries (1 entry for each desktop flow run).

And Cloud flow runs will not be logged into the Flow Session or Flow Session Trance entities.

**Comment by McKiko030** [comment]
Hi Praveen,

Hello, thanks for looking at this.

Here is the simple scenario. I run a metered cloud flow with 1 action to run a desktop flow.
The flow session trace recorded 3 run flow sessions. So, in the dashboard, it shows 3 flow runs instead of 1 flow run and the savings realized have been multiplied by 3x instead of 44.27$ because I only run the metered cloud flow once.

<img width="826" alt="Flow Sessions" src="https://github.com/user-attachments/assets/4a2ee7ff-6489-489f-9e90-2ce5450b3470">
[
<img width="785" alt="Dashboard" src="https://github.com/user-attachments/assets/1e23fb51-26de-41dc-8330-6728b6b80f0b">
](url)

**Comment by McKiko030** [comment]
Hi Praveen,

Good day! Thanks for looking on this.

Here is simple test.

I have metered cloud flow with 1 action to run a desktop flow.
I have run 3 times.
<img width="397" alt="FlowRun" src="https://github.com/user-attachments/assets/b91c79cd-d831-468d-848a-4b50a1a5f036">

In flow session traces, 4 have been recorded 
<img width="819" alt="FlowSessionTraces" src="https://github.com/user-attachments/assets/98482e16-7652-4dea-aca6-a5b2986234fc">

In dashboard, it displays 4 flow runs instead of 3. Our savings realized per instance is $44.27.
But it has a total of $177.08 which is $44.27 multiplied by 4.
It should only be multiplied by 3 with a total of $132.81 since I only run the metered cloud flow by 3 times.
<img width="782" alt="Dashboard" src="https://github.com/user-attachments/assets/a0e0feac-5c06-49e2-94e9-1fcbb1a3dfbf">

I agreed that there is no issue in the "Sync Flow Session Trace (Flow Session Trigger)".
According to Microsoft, the record in the table named "Flow Session" is being modified multiple times which will trigger the "Sync Flow Session Trace (Flow Session Trigger)" multiple times as well and create duplicate Flow Session Id in "Flow Session Traces".

**Comment by praveen-pulagam-gl** [comment]
@McKiko030 Thanks for the details. Yes, I agree on Flow Runs count. It should be number of desktop flow runs. And on the ROI actuals, I will get back to you on the ROI calculation whether it should be calculated per number of runs or number of updates (number of changes made to the desktop flow run record).

**Comment by McKiko030** [comment]
Hi @praveen-pulagam-gl, any updates?

**Comment by praveen-pulagam-gl** [comment]
@McKiko030 The ROI calculation also should be based on number of desktop flow runs and it should be corrected in the PowerBI dashboard file. We are working on it.

**Comment by McKiko030** [comment]
Hi @praveen-pulagam-gl, any progress?

**Comment by praveen-pulagam-gl** [comment]
@McKiko030 The ROI calculation & the count has been corrected and validation is in progress.

**Comment by McKiko030** [comment]
Hi @praveen-pulagam-gl, that's good to hear. May we know when do you plan to release the fix?

**Comment by praveen-pulagam-gl** [comment]
@McKiko030 Planned to release next week.

**Comment by carloangelo-reyes** [comment]
Hi @praveen-pulagam-gl,

Just following up on this.

**Comment by carloangelo-reyes** [comment]
Hi @praveen-pulagam-gl 

Good day!

We just would like to know when the fix to be released.

**Comment by praveen-pulagam-gl** [comment]
Hi @carloangelo-reyes We are facing some deployment issue in the pipeline. Deployment team is working on the issue. I will update here once the issue with deployment is resolved. Thanks!

**Comment by carloangelo-reyes** [comment]
Hi @praveen-pulagam-gl 

Good day! It's been 3 weeks already since the last update. When is the new target release date?

Regards,
Carlo

**Comment by praveen-pulagam-gl** [comment]
Hi @carloangelo-reyes, Apologies for the delay. We are still facing an issue in the release pipeline which causes the delay. We expect the fix in this week and will give an update early next week. Thanks!

**Comment by praveen-pulagam-gl** [comment]
Hi @carloangelo-reyes,

The issue with ROI calculation has been resolved and the fix is available in the latest release. Below is the latest release url
[AutomationKit.zip](https://github.com/microsoft/powercat-automation-kit/releases/download/AutomationKit-September2024/AutomationKit.zip)

**Comment by carloangelo-reyes** [comment]
Hi @praveen-pulagam-gl 

Thanks for fixing our issue. I confirmed that the duplicate flow session is now removed in the report.

<img width="842" alt="AutomationReport" src="https://github.com/user-attachments/assets/e8d15279-00f5-4590-8bed-36fd9880200b">

Did you just remove the duplicate in the report? Are we still seeing a duplicate session in the flow session table?

Also, I can't upgrade or update our solution to the latest release due to it being a same version number as the prev release.
<img width="311" alt="image" src="https://github.com/user-attachments/assets/4d15bbcc-02a5-491c-8414-cc8aff40319d">

Please advise if we need to uninstall the current version and then install the latest release.

**Comment by praveen-pulagam-gl** [comment]
@carloangelo-reyes 

We have corrected the Flow Runs & ROI actuals section data in the PowerBI Dashboard. We didn't remove the duplicate session entries in the Flow Session Trace table as it is as per the design. You can refer my [earlier comment](https://github.com/microsoft/powercat-automation-kit/issues/408#issuecomment-2232706936) on duplicate entries.

There is no change in satellite solution. So, it has the same version as previous.

Thanks!

**Comment by carloangelo-reyes** [comment]
Thanks for the info. We will review and test it further.
